### ISSUE TITLE
Video link in README

### ISSUE THREAD

**Issue by soosub** [taldatech/deep-latent-particles-pytorch#1]
Hey! Just a heads up that the link to the video in the README is dead. Where can I find the video?

![image](https://user-images.githubusercontent.com/44366402/176813377-4ddf6b11-e509-4fbf-beaa-38e5aecd1b4d.png)

Awesome work btw 😍

**Comment by taldatech** [comment]
Thank you so much for the kind words! Yeah, the video link is still a placeholder as there is no video yet, but hopefully there will one available next month. I will update the link once it is uploaded. Thanks!
