### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by pooja12295** [taldatech/deep-latent-particles-pytorch#2]
What is the training time for various datasets for your code?

**Comment by taldatech** [comment]
Hi,
It depends on the resolution, the size of the data and th enumber of GPUS available.
You can get an impression by running the Colab example we provided for the Shapes datasets (64x64, 20,000 examples), which takes about 2-3 hours to get good performance on a single GPU.
Traffic - 128x128, ~40,000 examples: 1-2 days of training.
Celeb - 128x128: 2-4 days (depending on the number of GPUs)
CLEVRER - 128x128: 3-6 days (depending on the number of GPUs)
