### ISSUE TITLE
Output dimensions of ObjectDecoderCNN

### ISSUE THREAD

**Issue by MoritzLange** [taldatech/deep-latent-particles-pytorch#3]
Hey,

first of all thanks a lot for providing this repository, very inspiring work!

I am adapting it to learn representations of my own data, which contains 256x256 pixel images. Training crashes with the error
```
[...]
File "[...]/models.py", line 371, in translate_patches
  grid = F.affine_grid(theta, padded_patches_batch.size(), align_corners=align_corners)
File "[...]/lib/python3.9/site-packages/torch/nn/functional.py", line 4341, in affine_grid
  return torch.affine_grid_generator(theta, size, align_corners)
RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [640, 3] but got: [160, 3].
```
The issue leading to this error is somewhere else: After a while I noticed that the forward method of ObjectDecoderCNN returns data with the wrong dimensions. After yet some more research, I discovered that this is because of a numerical instability in modules/modules.py, in `ObjectDecoderCNN.__init__()`, line 630 ([direct link](https://github.com/taldatech/deep-latent-particles-pytorch/blob/37f3bdc5894699ec9c28f61b96aba2236e6de026/modules/modules.py#L630C24-L630C24)):

`num_upsample = int(np.log(patch_size[0]) // np.log(2)) - 3`
is supposed to calculate the logarithm to the base 2 of the number of patches, right? It does calculate the correct logarithm (minus 3) when `patch_size[0]` is 8, 16, or 32. But since my input images have 256x256 pixels, they result in 64 patches. For 64 and 128 patches you'll get the wrong number, 1 less than what you want to get. This results in the network not having the correct amount of layers, so it returns the wrong output shapes and the entire model crashes.

Fix:
Replace line 630 with 
`num_upsample = int(np.log2(patch_size[0])) - 3`

I just wanted to point this out in case someone encounters the same error, which will happen for input images that are large enough to result in 64 or even 128 patches.

Cheers
Moritz

**Comment by taldatech** [comment]
This is awesome! Thank you for catching this. I updated that line (with credit for you).
We were not able to train at this resolutions for compute reasons, so it is very nice that you can!
We have an updated version (DLPv2) which is more lightweight and accurate, and we should drop the code around next month (https://github.com/taldatech/ddlp).
Please free to reach out to me if you have any questions or need assistance with anything related to DLP.
Thanks again!

**Comment by MoritzLange** [comment]
Glad to help! And thanks for the heads-up concerning DDLP, I'm looking forward to it!

**Comment by MoritzLange** [comment]
Glad to help! And thanks for the heads-up regarding DDLP, I'm looking forward to it!

**Comment by MoritzLange** [comment]
Sorry for reopening this, I didn't have time to run the full training before making my initial post, so until now I had missed the fact that the same issue appears in line 719 of modules/modules.py as well!

**Comment by taldatech** [comment]
You are correct, should be fixed now, thanks!
